// Generates INDEX.md: every script, its description and a one-click install link.
// Usage: npm run index            (reads the working tree)
//        node tools/index.mjs --staged   (reads the git index; used by the pre-commit hook)

import fs from 'node:fs';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import { ROOT, metaValue, metaValues, rawUrl, readScripts } from './lib.mjs';

export const INDEX_FILE = 'INDEX.md';

function cell(text) {
    return String(text).replace(/\|/g, '\\|').replace(/\s*\n\s*/g, ' ');
}

export function buildIndex({ staged }) {
    const scripts = readScripts({ staged: staged });
    const lines = [
        '# Userscripts',
        '',
        '<!-- Generated by tools/index.mjs (runs in the pre-commit hook). Do not edit by hand. -->',
        '',
        'Click **Install** with Tampermonkey enabled. Installed scripts auto-update from `main`.',
        '',
    ];

    if (scripts.length === 0) {
        lines.push('_No scripts yet. Create one with `npm run new -- <name> <match-url>`._');
        lines.push('');
        return lines.join('\n');
    }

    lines.push('| Script | Description | Runs on | Version | Install |');
    lines.push('| --- | --- | --- | --- | --- |');
    for (const script of scripts) {
        const meta = script.meta || [];
        const name = metaValue(meta, 'name') || script.fileName;
        const description = metaValue(meta, 'description') || '';
        const version = metaValue(meta, 'version') || '';
        const matches = metaValues(meta, 'match').concat(metaValues(meta, 'include'));
        const runsOn = matches.map((m) => `\`${m}\``).join('<br>');
        const source = `[${cell(name)}](${script.repoPath})`;
        const install = `[Install](${rawUrl(script.fileName)})`;
        lines.push(`| ${source} | ${cell(description)} | ${runsOn} | ${cell(version)} | ${install} |`);
    }
    lines.push('');
    return lines.join('\n');
}

export function writeIndex({ staged }) {
    const target = path.join(ROOT, INDEX_FILE);
    const next = buildIndex({ staged: staged });
    let current = null;
    if (fs.existsSync(target)) {
        current = fs.readFileSync(target, 'utf8');
    }
    if (current === next) {
        return false;
    }
    fs.writeFileSync(target, next);
    return true;
}

if (import.meta.url === pathToFileURL(process.argv[1]).href) {
    const changed = writeIndex({ staged: process.argv.includes('--staged') });
    if (changed) {
        console.log(`Updated ${INDEX_FILE}`);
    } else {
        console.log(`${INDEX_FILE} is up to date`);
    }
}
